# Generated by Django 3.1.1 on 2021-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('displayed', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
